export const SSO_LOGIN_SERVER_URL = "https://d-testline.herokuapp.com"
export const SERVER_URL_HEROKU = "https://dartmart-main-server.herokuapp.com"
export const SERVER_URL_RENDER = "https://stripeserver.onrender.com"
export const ROUTE_SSO_LOGIN = "/sso_login"
export const ROUTE_SSO_LOGOUT = "/sso_logout"
export const ROUTE_PAYMENT_SHEET = "/payment-sheet"
export const ROUTE_CUSTOMERS = "/v1/customers"
